wandb_version: 1

K:
  desc: null
  value: 2000
_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    start_time: 1647967894
    t:
      1:
      - 1
      - 5
      - 30
      - 41
      3:
      - 16
      4: 3.7.9
      5: 0.12.11
      8:
      - 5
batch_size:
  desc: null
  value: 16
lr:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.999
